Feature/sign up
tepaevayuliya/todo pull request #1
Opened 2023-11-06 20:41 UTC by tepaevayuliya

2023-11-07 15:51 UTC, tepaevayuliya commented
В сториборде SignUp (как и в других сделанных стробордах) нижний отступ должен быть равен 16, а не 35, если что. Забыла поправить это перед тем, как сделать пул реквест.

2023-11-07 17:05 UTC, Boslana commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +
Возможно лишняя строка

2023-11-07 17:17 UTC, Boslana commented
1) todo.xcodeproj/xcuserdata/tepaevayuliya.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist - это должно быть на гите?

2023-11-09 12:57 UTC, Boslana commented on todo/Classes/Modules/Auth/AuthViewController.swift
> +        let backItem = UIBarButtonItem()
Можно упростить.

2023-11-09 13:53 UTC, Boslana commented on todo/UIKit/TextInput.swift
> +    func isEmpty() -> Bool {
Можно вот так 
        return textField.text == ""

2023-11-09 14:15 UTC, aps21 requested changes

2023-11-09 14:19 UTC, tepaevayuliya commented on todo/UIKit/TextField.swift
> +        isSecureTextEntry = true
Потому что по дизайну там нет этого «глазика»

2023-11-09 14:21 UTC, tepaevayuliya commented on todo/Classes/Modules/SignUp/SignUpViewController.swift
> +        }
Планировала добавить потом, когда прикрутим полноценную проверку

2023-11-09 14:30 UTC, aps21 commented on todo/UIKit/TextInput.swift
> +    func isEmpty() -> Bool {
из минусов - нет проверки на nil

2023-11-09 14:50 UTC, Boslana commented on todo/UIKit/TextInput.swift
> +    func isEmpty() -> Bool {
return (textField.text == "" || textField.text == nil) а так?)

2023-11-09 14:52 UTC, aps21 commented on todo/UIKit/TextInput.swift
> +    func isEmpty() -> Bool {
можно даже textField.text?.isEmpty != true

2023-11-12 17:04 UTC, merged