Feature/text view
tepaevayuliya/todo pull request #2
Opened 2023-11-14 10:12 UTC by tepaevayuliya

2023-11-15 16:32 UTC, Boslana requested changes

2023-11-16 10:53 UTC, aps21 requested changes

2023-11-19 11:43 UTC, tepaevayuliya commented on todo/UIKit/TextViewInput.swift
> +                                  height: 22)
Не вижу проблемы, автоматическое выравнивание кода оставляет все в таком же виде. Могу записать всё в одну строку, если нужно

2023-11-19 13:25 UTC, merged

2023-11-19 17:21 UTC, aps21 commented on todo/UIKit/TextViewInput.swift
> +                                  height: 22)
CGRect( - на одной строке
остальное на других
) - последняя