Add profile screen and SnackBar
tepaevayuliya/todo pull request #8
Opened 2023-12-12 08:58 UTC by tepaevayuliya

2023-12-12 11:32 UTC, Boslana requested changes

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Main/MainViewController.swift
> +
можно вынести в отдельный файлик (как все остальные структуры)

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +        self.view.window?.rootViewController = storyboard.instantiateInitialViewController()
возможно стоит обернуть в DispatchQueue.main.async

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +        errorLabel.font = UIFont.systemFont(ofSize: 18, weight: .semibold)
по дизайну размер 15

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +            window.addSubview(errorView)
вроде можно просто использовать view.window?. (без 33-35 строк)

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +        errorLabelTopConstraint.isActive = true
Для errorView и errorLabel наверно лучше поставить translatesAutoresizingMaskIntoConstraints = false до активации constraint

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +    func showSnackbarVC(massage: String) {
m**e**ssage, у меня тоже такая ошибка была)

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +        navigationItem.backButtonDisplayMode = .minimal
можно удалить строку, есть в ParentViewController )
в MainViewController тоже )

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +                self.view.window?.rootViewController = storyboard.instantiateInitialViewController()
можно использовать функцию goToAuth()

2023-12-12 11:32 UTC, Boslana commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +    private func getprofileImageView() {
для соблюдения стиля лучше переименовать в getProfileImageView)

2023-12-13 06:22 UTC, irina-gs requested changes

2023-12-13 06:22 UTC, irina-gs commented on todo/Resources/Storyboards/Profile.storyboard
> +                                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAlignment=
Наверное нужно убрать text="Label", потому что если запрос на получение имени пользователя не проходит, то под картинкой отображается "Label"

2023-12-13 06:22 UTC, irina-gs commented on todo/Classes/Modules/Main/MainViewController.swift
> +                        self.showSnackbarVC(massage: error.localizedDescription)
Не отображается снек бар (возможно из-за приведения к типу NetworkError)
И в аналогичных местах тоже самое(

2023-12-13 06:22 UTC, irina-gs commented on todo/Classes/Modules/Auth/AuthViewController.swift
> +                        if UserManager.shared.accessToken == nil {
Тут точно нужно что условие?

2023-12-13 22:13 UTC, merged