Feature/image picker and multipart form data
tepaevayuliya/todo pull request #9
Opened 2023-12-19 07:47 UTC by tepaevayuliya

2023-12-19 17:53 UTC, Boslana requested changes

2023-12-19 19:10 UTC, irina-gs requested changes

2023-12-19 19:10 UTC, irina-gs commented on todo/Network/NetworkManager.swift
>          }
Возможно стоит перенести в else (79 строка)

2023-12-22 14:41 UTC, aps21 requested changes

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Auth/AuthViewController.swift
> +                    _ = try await NetworkManager.shared.signIn(email: emailTextField.text ?? "", password: passwordTextField.text ?? "")
ну, понятно, заменить все на DIP

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +        }
можно сделать более сложный кейс - рефреш крутится, пока идет запрос
когда пришел ответ/ошибка - рефреш скрывается

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +        }
можно взять у collectionView.numberOfItems in section

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Main/MainViewController.swift
> +        collectionView.scrollToItem(at: IndexPath(item: count - 1, section: 1), at: .bottom, animated: false)
мб если с анимацией, то норм будет работать?

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Parent/ParentViewController.swift
>      private lazy var errorLabelTopConstraint = errorLabel.topAnchor.constraint(equalTo: errorView.topAnchor, constant: 6)
давай вынесем всю логику снека в отдельный класс
в паренте будет только переменная этого класса, уже в нем будешь дергать методы показать/скрыть
а то оч много в родителе кода

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +        }
давай guard?
зачем нам что-то делать со снеком, если мы его не добавили на экран

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Parent/ParentViewController.swift
> +    private func cancelSnackBar() {
hide

2023-12-22 14:41 UTC, aps21 commented on todo/Classes/Modules/Profile/ProfileViewController.swift
> +        if UIImagePickerController.isSourceTypeAvailable(.photoLibrary){
swiftformat .

2023-12-22 14:41 UTC, aps21 commented on todo/Network/NetworkManager.swift
> +        let userImage = image.jpegData(compressionQuality: 0.2)
0.9
или через [UIGraphicsImageRenderer](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer) вписывай в максимум 1000 по одной стороне

2023-12-22 14:42 UTC, aps21 commented
если нет картинки, то отображается белый фон
вообще непонятно куда жмакать)
можешь либо заглушку, либо серый кружок

2023-12-22 14:43 UTC, aps21 commented
пока грузится картинка - нет индикации, что она грузится
мне как пользователю непонятно, могу ли я уйти с экрана или что-то еще там делается

2023-12-22 14:45 UTC, aps21 commented
на профиле в идеале, конечно, продумать как можно повторить запрос, но не блочить выход из профиля
мб вместо картинки кнопку какую-то)
но можно не делать в этой домашке

2023-12-28 13:06 UTC, merged